// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using w13_containers.Data;

#nullable disable

namespace w9_efcore_intro.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("w13_containers.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("HomeRoomId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("StatsId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("w13_containers.Models.CharacterStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Containers");

                    b.HasDiscriminator<string>("ContainerType").HasValue("Container");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("w13_containers.Models.Containers.EquipmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedItemId")
                        .HasColumnType("int");

                    b.Property<int>("slotType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquippedItemId");

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("w13_containers.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContainerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EligibleSlot")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("w13_containers.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MonsterType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Monsters");

                    b.HasDiscriminator<string>("MonsterType").HasValue("Monster");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("w13_containers.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EastRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NorthRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("SouthRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("WestRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EastRoomId");

                    b.HasIndex("NorthRoomId");

                    b.HasIndex("SouthRoomId");

                    b.HasIndex("WestRoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.Chest", b =>
                {
                    b.HasBaseType("w13_containers.Models.Containers.Container");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredKeyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Chest");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.Equipment", b =>
                {
                    b.HasBaseType("w13_containers.Models.Containers.Container");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.Inventory", b =>
                {
                    b.HasBaseType("w13_containers.Models.Containers.Container");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Inventory");
                });

            modelBuilder.Entity("w13_containers.Models.Items.Armor", b =>
                {
                    b.HasBaseType("w13_containers.Models.Items.Item");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("w13_containers.Models.Items.Consumable", b =>
                {
                    b.HasBaseType("w13_containers.Models.Items.Item");

                    b.Property<int>("EffectAmount")
                        .HasColumnType("int");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("w13_containers.Models.Items.KeyItem", b =>
                {
                    b.HasBaseType("w13_containers.Models.Items.Item");

                    b.Property<string>("KeyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("KeyItem");
                });

            modelBuilder.Entity("w13_containers.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("w13_containers.Models.Items.Item");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("w13_containers.Models.Goblin", b =>
                {
                    b.HasBaseType("w13_containers.Models.Monster");

                    b.Property<int>("Sneakiness")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Goblin");
                });

            modelBuilder.Entity("w13_containers.Models.Troll", b =>
                {
                    b.HasBaseType("w13_containers.Models.Monster");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Troll");
                });

            modelBuilder.Entity("w13_containers.Models.Character", b =>
                {
                    b.HasOne("w13_containers.Models.Containers.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("w13_containers.Models.Room", "HomeRoom")
                        .WithMany()
                        .HasForeignKey("HomeRoomId");

                    b.HasOne("w13_containers.Models.Containers.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("w13_containers.Models.CharacterStats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("HomeRoom");

                    b.Navigation("Inventory");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.EquipmentSlot", b =>
                {
                    b.HasOne("w13_containers.Models.Containers.Equipment", "Equipment")
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("w13_containers.Models.Items.Item", "EquippedItem")
                        .WithMany()
                        .HasForeignKey("EquippedItemId");

                    b.Navigation("Equipment");

                    b.Navigation("EquippedItem");
                });

            modelBuilder.Entity("w13_containers.Models.Items.Item", b =>
                {
                    b.HasOne("w13_containers.Models.Containers.Container", "Container")
                        .WithMany("Items")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Container");
                });

            modelBuilder.Entity("w13_containers.Models.Monster", b =>
                {
                    b.HasOne("w13_containers.Models.Room", "Room")
                        .WithMany("Monsters")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("w13_containers.Models.Room", b =>
                {
                    b.HasOne("w13_containers.Models.Room", "EastRoom")
                        .WithMany()
                        .HasForeignKey("EastRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("w13_containers.Models.Room", "NorthRoom")
                        .WithMany()
                        .HasForeignKey("NorthRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("w13_containers.Models.Room", "SouthRoom")
                        .WithMany()
                        .HasForeignKey("SouthRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("w13_containers.Models.Room", "WestRoom")
                        .WithMany()
                        .HasForeignKey("WestRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EastRoom");

                    b.Navigation("NorthRoom");

                    b.Navigation("SouthRoom");

                    b.Navigation("WestRoom");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.Container", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("w13_containers.Models.Room", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("w13_containers.Models.Containers.Equipment", b =>
                {
                    b.Navigation("EquipmentSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
